### ISSUE TITLE
Strand-Cam BackendError: Node is not writable upon camera initiation

### ISSUE THREAD

**Issue by elhananby** [strawlab/strand-braid#15]
Hello Andrew,

I started having this weird error occurring today. I rebooted my computer after a while, and at first it threw a lot of `Negative acquisition duration?` errors for two of the cameras. I tried to disconnect and reconnect all the cameras, and now several of the cameras shows this error upon initiation:
```
strand_cam: BackendError(PylonError(Pylon::GenericException: Node is not writable. : AccessException thrown in node 'DeviceFeaturePersistenceStart' while calling 'DeviceFeaturePersistenceStart.Execute()' (file 'CommandT.h', line 61)))    
```
I've attached the entire terminal output for the `braid-run` command.
[terminal_output.txt](https://github.com/strawlab/strand-braid/files/8063327/terminal_output.txt)

Thanks
Elhanan

**Comment by astraw** [comment]
I'm not entirely sure but perhaps the initial `Negative acquisition duration?` errors are due to your computer's clock slewing to synchronized with an NTP or PTP time source? Does it go away if you leave the computer running for a while and then restart braid? You may also be able to bypass initial slewing with something like `ntpdate` which will probably get your clock within a few msec of correct very quickly. This is basically just a guess, though.

The `DeviceFeaturePersistenceStart` error is also strange. The release you are using (0.11.1) is a couple months old and I cannot understand why it would suddenly have new behavior. Did you change any settings in the configuration file? I do seem to vaguely remember something like this, although perhaps not this exact error, when trying to get loading and saving settings from Pylon .pfs files ? Did you update your Pylon drivers?

**Comment by elhananby** [comment]
Okay, so it seems the `Negative acquisition duration` error was solved by using `ntpdate` to correct the clock.
Regarding the `DeviceFeaturePersistenceStart` error: I basically did a fresh install of both Pylon and Braid, as well as power-cycled all the cameras, and that seems to have solved it.
I still have no idea what caused it initially.

Thank you for the very quick reply!
